### ISSUE TITLE
Code at the Edge-2017 package

### ISSUE THREAD

**Issue by faraz2023** [code-at-the-edge/project#14]
[cal-url.txt](https://github.com/code-at-the-edge/project/files/2613666/cal-url.txt)
[History.txt](https://github.com/code-at-the-edge/project/files/2613667/History.txt)

The stuff from the workshop of 2017

**Comment by dcwalk** [comment]
We discussed while co-working on 2018-12-03 that the materials captured in the [`kcc-workshop`](https://github.com/code-at-the-edge/kcc-workshop) are sufficient as a snapshot from the first iteration! 

I'm closing this as done 🎉
