### ISSUE TITLE
Research alternative hosted code pen/editors 

### ISSUE THREAD

**Issue by dcwalk** [code-at-the-edge/project#3]
Current implementation uses [JSbin](https://jsbin.com/?html,output), [`gh repo`](https://github.com/jsbin/jsbin)

Others:
  - [Thimble](https://thimble.mozilla.org/en-US/)
  - [html house](https://html.house/) <-- ??
  - [codepan](https://codepan.net/)

Would be good to review and research alternatives with an eye to better understanding/evaluating against project needs

**Comment by chinchang** [comment]
The fastest offline frontend playground out there -> Web maker https://webmakerapp.com/ :)

**Comment by titaniumbones** [comment]
I'm keeping notes on various editors i nthe PRD for now: https://hackmd.io/Ci5kwXOoTLSFabpThfuuBg?both#Features-and-%E2%80%9Cnon-functional%E2%80%9D-requirements

**Comment by titaniumbones** [comment]
We should be reaching out do devs:

- [x] web-maker
- [x] thimble
- [ ] html house
- [-] peer pad

**Comment by dcwalk** [comment]
We filled out the PRD with these examples and tried to identify strengths and gaps. I'm going to close this as we'll be working forward to document needed features in #15
